### ISSUE TITLE
Gcc_flag issue with Max os

### ISSUE THREAD

**Issue by xjing76** [aesara-devs/aemcmc#106]
Does it make sense to add in the flag settings by default to avoid the issue with Mac?
I have to set those flag manually every time I set up a new environment on Mac. 

```
aesara.config.warn_float64 = 'ignore'
aesara.config.gcc__cxxflags = "-Wno-narrowing"
```

**Comment by brandonwillard** [comment]
The underlying issue is https://github.com/aesara-devs/aesara/issues/127.  We need to merge the associated PR: https://github.com/aesara-devs/aesara/pull/972.  

Thanks for reporting it; we'll do that ASAP (ideally before we forget again).
