### ISSUE TITLE
Assign NUTS sampler to remaining variables

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aemcmc#47]
We need to assign the NUTS sampler to the remaining (continuous) variables [here](
https://github.com/aesara-devs/aemcmc/blob/213e0fd105f57b3f41eb1423d966962512c25ec3/aemcmc/basic.py#L107) in `aemcmc.basic.construct_sampler`.

**Comment by rlouf** [comment]
I am currently not sure how to handle the sampler parameters in this situation. The caller has to know that the sampling step requires to pass extra parameters and I am not sure how that can be done in a way that both a machine and a human would understand. I was first thinking of passing instructions in the form of a string, but this is not a good idea, at least not in AeMCMC: it complicates handling of these step functions by a program downstream. But I know think this should be handled at the type level e.g. with `SamplingAlgorithm` and `ParametrizedSamplingAlgorithm`. `NUTS` would be a `ParametrizedSamplingAlgorithm` and contain the necessary information about its parameters (type, rank for instance).

**Comment by brandonwillard** [comment]
> I am currently not sure how to handle the sampler parameters in this situation. The caller, either machine or human, has to know that the sampling step requires extra parameters. I was first thinking of passing instructions in the form of a string, but this is not a good idea, at least not in AeMCMC: it complicates handling of these step functions by a program downstream.

Can you provide pseudo-code examples for the relevant scenarios(s)?  Without something like that, I'm not confident that I would end up addressing all the relevant concerns together.

**Comment by rlouf** [comment]
I'll do better than that and open a PR shortly with what I'm more or less sure of and add the explanation there.
