### ISSUE TITLE
Add support for recentering and rescaling

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aemcmc#5]
Just like https://github.com/aesara-devs/aemcmc/issues/4, we need to incorporate the recentering and rescaling from `symbolic-pymc` (see the example [here](https://pymc-devs.github.io/symbolic-pymc/theano-radon-example.html)).

**Comment by rlouf** [comment]
Is there any particular reason why you would want to
implement this here and not in `aeppl`? I remember talks about automatic marginalization of RVs with discrete support in the repo (but couldn't find the relevant issue), and that would fall under the same umbrella.
