### ISSUE TITLE
Set `filterwarnings` to `error` in the tests

### ISSUE THREAD

**Issue by brandonwillard** [aesara-devs/aemcmc#54]
Our tests should not allow un-caught/checked warnings.

The addition to `setup.cfg` mentioned [here](https://docs.pytest.org/en/7.1.x/how-to/capture-warnings.html) should be sufficient.  We'll need to update our tests to prevent them from failing, though.

**Comment by rlouf** [comment]
Addressed in https://github.com/aesara-devs/aemcmc/commit/e0336b62adbbd13755500fc0616964903b3b7a10
