### ISSUE TITLE
Move PolyaGammaRV upstream in aesara?

### ISSUE THREAD

**Issue by rlouf** [aesara-devs/aemcmc#7]
I was wondering if it would make sens to move the implementation of `PolyaGammaRV` from this repo to `aesara`?

**Comment by zoj613** [comment]
I believe the main repo only wraps the core distributions offered by scipy/numpy, this is why there was a removal in recent commit: https://github.com/aesara-devs/aesara/commit/d4fe4c3f9c223517e78e24252cbb0af39e47ee82

**Comment by rlouf** [comment]
Ah I see it is using another library you implemented. Maybe it would make sense to move this upstream ? 

I’m just afraid that we'll end up with some distributions in `aemcmc`, some in `aeppl`, etc

A solution would be to have a library dedicated to distributions, with sampling function (many would be a wrapper around `aesara`'s) and logpdfs. It would grow independently from @aesara-devs/aeppl and this library. Thoughts @brandonwillard @ricardoV94

**Comment by brandonwillard** [comment]
Creating a distinct repository is fine, but we definitely don't want to add non-NumPy distributions to Aesara.

**Comment by rlouf** [comment]
Ok, closing for now. We can revisit the idea of creating a distinct repository when we start using several non-numpy distributions in different aesara projects.
