### ISSUE TITLE
Make `horseshoe_nbinom_gibbs` return a kernel

### ISSUE THREAD

**Issue by rlouf** [aesara-devs/aemcmc#8]
The current version of `horseshoe_nbinom_gibbs` includes a `scan` loop to get samples using the kernel defined inside the function. However, to be able to compose this kernel with others we need to be able to build its graph independently from any sampling loop.

**Comment by zoj613** [comment]
That makes sense. How would you consider we refactor this so that we can accommodate those who want to sample directly without  building their own scan loop and those who want to compose their own.

**Comment by rlouf** [comment]
> Im gussing we'd need another function like `get_samples` that takes the `step_fn` kernel and initial values as arguments and then calls scan internally?

That's the idea yes.

**Comment by rlouf** [comment]
We should emulate what we do in #35 for the NUTS kernel and come up with a framework for state passing that is compatible with all kernels and sampling steps.
